### ISSUE TITLE
Test: Float test fail

### ISSUE THREAD

**Issue by kennarddh** [ValerioCipolla/vrandom#65]
```bash
 FAIL  tests/float.test.js
  ● float › should return a number between min and max

    expect(received).toBeLessThan(expected)

    Expected: < 1
    Received:   1

      40 |   it("should return a number between min and max", () => {
      41 |     expect(float(0, 1)).toBeGreaterThanOrEqual(0);
    > 42 |     expect(float(0, 1)).toBeLessThan(1);
         |                         ^
      43 |   });
      44 |
      45 |   it("should return a number with the specified number of decimals", () => {

      at Object.<anonymous> (tests/float.test.js:42:25)
```

**Comment by kennarddh** [comment]
I try this
```js
const float = require("./lib/float.js");

let x = 0;
let y = 0;

const min = 0;
const max = 10;

for (let i = 0; i < 1000000; i++) {
  const result = float(min, max);

  if (result === max) {
    x++;
  } else if (result > max) {
    y++;
  }
}

console.log(`${x}/${y}`);
```

Result:
```bash
$ node test.js
529/0
```

Is max included?

**Comment by ValerioCipolla** [comment]
Yes thank you for opening this issue, so the toFixed method is rounding up the floating point value which means that sometimes vrandom.float(min, max) can return a value equal to max. Now, because I have change the int function to return a number including max, I am happy to keep float like that, all that is needed is changing the docs and changing the tests  to make sure we are not testing for the returned value to be strictly less than max. I will close this issue and open new ones to get those things fixed. Thank you for spotting that
